### PR TITLE
New questions client intake

### PR DESCRIPTION
**Pull request by shobhitpuri**
_Note_: Please do not merge it yet. This works fine for iPhones. However the text gets cutoff for low resolution iPads. I tried to put all the elements on this new screen inside a `UIScrollView`. However I'm having a hard time getting the constraints right. Event when I get the constraints right, it doesn't scroll on the simulator.

### CODE REVIEW

**Comment by shobhitpuri** [comment]
[Add 2 questions to the client intake:](https://trello.com/c/jYMA2TDl/64-add-2-questions-to-the-client-intake)

**Comment by supadupdip** [comment]
Hey @shobhitpuri take a look at the latest push see if everything is working correctly and if you want to make any improvements

**Comment by shobhitpuri** [comment]
@supadupdip It seems to be scrolling now. Thanks. However for iPad, the scrollview hides behind the `next` button. I will try to fix that.

**Comment by shobhitpuri** [comment]
Updated the PR to fix overlapping issue. Looks good to merge now. 👍 Let me know if there is anything else that needs attention here.

**Pull request merged**
